/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    Editors: typeof import('./src/components/Editors.vue')['default']
    EditorView: typeof import('./src/components/EditorView.vue')['default']
    GenPanel: typeof import('./src/components/GenPanel.vue')['default']
    Hydra: typeof import('./src/components/Hydra.vue')['default']
    HydraStage: typeof import('./src/components/HydraStage.vue')['default']
    Hyground: typeof import('./src/components/Hyground.vue')['default']
    ICarbonSendActionUsage: typeof import('~icons/carbon/send-action-usage')['default']
    IFa6RegularCirclePause: typeof import('~icons/fa6-regular/circle-pause')['default']
    IFa6SolidBackwardFast: typeof import('~icons/fa6-solid/backward-fast')['default']
    IFa6SolidBackwardStep: typeof import('~icons/fa6-solid/backward-step')['default']
    IFa6SolidDiceD6: typeof import('~icons/fa6-solid/dice-d6')['default']
    IFa6SolidFileExport: typeof import('~icons/fa6-solid/file-export')['default']
    IFa6SolidFileImport: typeof import('~icons/fa6-solid/file-import')['default']
    IFa6SolidFilm: typeof import('~icons/fa6-solid/film')['default']
    IFa6SolidForwardFast: typeof import('~icons/fa6-solid/forward-fast')['default']
    IFa6SolidForwardStep: typeof import('~icons/fa6-solid/forward-step')['default']
    IFa6SolidGear: typeof import('~icons/fa6-solid/gear')['default']
    IFa6SolidPlay: typeof import('~icons/fa6-solid/play')['default']
    IFa6SolidShuffle: typeof import('~icons/fa6-solid/shuffle')['default']
    IFa6SolidSliders: typeof import('~icons/fa6-solid/sliders')['default']
    IFa6SolidTrashCan: typeof import('~icons/fa6-solid/trash-can')['default']
    ILetsIconsBoxRefreshAltRight: typeof import('~icons/lets-icons/box-refresh-alt-right')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    IMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    IMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit')['default']
    IMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    InActorPanel: typeof import('./src/components/InActorPanel.vue')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    PlayAudio: typeof import('./src/components/PlayAudio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedDeviceTest: typeof import('./src/components/SharedDeviceTest.vue')['default']
    Splitter: typeof import('./src/components/Splitter.vue')['default']
    StagePanel: typeof import('./src/components/StagePanel.vue')['default']
    TopLevel: typeof import('./src/components/TopLevel.vue')['default']
  }
}
